=== EGA-archive/beacon2-ri-tools-v2/ref_schemas/EUCAIM-Schema-main/DiseaseMetadata.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Disease patient attributes",
  "type": "object",
  "properties": {
    "diseaseId": {
      "type": "string",
      "description": "Unique identifier for the diagnostic/disease. This field was not in the original EUCAIM Federated Query metadata.",
      "example": "X123456-D01"
    },
    "patientId": {
      "type": "string",
      "description": "A unique identifier for the patient. Should match the Patient ID DICOM tag (0010,0020) and anonymization processes.",
      "example": "X123456"
    },
    "ageAtDiagnosis": {
      "type": "number",
      "description": "Age of the patient at the time the tumor or lesion was confirmed.",
      "example": 45.6
  },
    "diagnosis":{
      "description": "Diagnosis of the disease.",
      "$ref": "./Common/OntologyTerm.json",
      "examples": [{
                    "id": "EUCAIM:CLIN1000075",
                    "label": "Malignant neoplasm of prostate"
                   },
                   {
                    "id": "EUCAIM:CLIN1000060",
                    "label": "Malignant neoplasm of breast"
                   },
                   {
                    "id": "EUCAIM:CLIN1000057",
                    "label": "Malignant neoplasm of colon"
                   },
                   {
                    "id": "EUCAIM:CLIN1000185",
                    "label": "Malignant neoplasm of rectum"
                   }
    ]
  },
    "yearOfDiagnosis": {
      "type": "integer",
      "description": "Date when the tumor was histologically confirmed or confirmed by imaging.",
      "example": "2022"
    },
    "dateOfFirstTreatment": {
      "type": "string",
      "format": "date",
      "description": "Date when first treatment occurred.",
      "example": "2024-03-01"
    },
    "pathologyConfirmation": {
      "description": "Method used to confirm pathology (e.g., histological biopsy or imaging for specific cases).",
      "$ref": "./Common/OntologyTerm.json",
      "examples": [{
                    "id": "EUCAIM:CLIN1001712",
                    "label": "Biopsy"
                   },
                   {
                    "id": "EUCAIM:CLIN1004598",
                    "label": "Excision"
                   }]
    },
    "pathology": {
      "description": "Histology and histological subtype of the lesion (ICD-O-3 if available).",
      "type": "array",
      "items": {
        "$ref": "./Common/OntologyTerm.json"
               },
      "example": [{
                    "id": "EUCAIM:CLIN1047138",
                    "label": "Adenocarcinoma"
                  },
                  {
                    "id": "EUCAIM:CLIN1063544",
                    "label": "Papillary carcinoma"
                  }]
    },
    "imagingProcedureProtocol": {
      "description": "Specific protocol applied to obtain the radiology diagnostic image.",
      "$ref": "./Common/OntologyTerm.json",
      "example": [{
                    "id": "EUCAIM:IMG1000076",
                    "label": "CT of thorax with contrast"
                  },
                  {
                    "id": "EUCAIM:IMG1000078",
                    "label": "CT of breast"
                  }]
    },
    "treatment": {
      "description": "Type of treatment received by the patient.",
      "type": "array",
      "items": {
        "$ref": "./Common/OntologyTerm.json"
               },
      "example": [
        {
                    "id": "EUCAIM:CLIN1024528",
                    "label": "Chemotherapy"
                },
                {
                    "id": "EUCAIM:COM1001099",
                    "label": "Surgery"
        }]
    }
},
  "required": [
    "diseaseId",
    "patientId",
    "ageAtDiagnosis",
    "diagnosis"
  ]
}

=== EGA-archive/beacon2-ri-tools-v2/files/deref_schemas/EUCAIM/DiseaseMetadata.json
{"diseaseId": "", "patientId": "", "ageAtDiagnosis": 0, "diagnosis": {"id": "", "label": ""}, "yearOfDiagnosis": 0, "dateOfFirstTreatment": "", "pathologyConfirmation": {"id": "", "label": ""}, "pathology": [{"id": "", "label": ""}], "imagingProcedureProtocol": {"id": "", "label": ""}, "treatment": [{"id": "", "label": ""}]}
