=== EGA-archive/beacon2-ri-tools-v2/ref_schemas/EUCAIM-Schema-main/ImageStudiesMetadata.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "EUCAIM Minimum Imaging Metadata",
  "type": "object",
  "properties": {
    "imageStudyId": {
      "type": "string",
      "description": "Unique identifier for the image. This field was not in the original EUCAIM Federated Query metadata.",
      "example": "X123456-IMG01"
    },
    "disease": {
      "description": "Disease information associated with the image.",
      "$ref": "./Common/Matrixes/DiseasesMetadata.json"
    },
    "imageModality": {
      "description": "Modality of the imaging study (DICOM tag 0008,0060), controlled vocabulary",
      "$ref": "./Common/Definitions.json#/$defs/ImageModality",
      "examples": [
        {
          "id": "EUCAIM:IMG1000026",
          "label": "Computed tomography"
        },
        {
          "id": "EUCAIM:IMG1000030",
          "label": "Mammography"
        }
      ]
    },
    "imageBodyPart": {
      "description": "Anatomical area imaged (DICOM tag 0018,0015), controlled vocabulary",
      "$ref": "./Common/Definitions.json#/$defs/BodyPart",
      "examples": [
        {
          "id": "EUCAIM:BP1000067",
          "label": "Chest"
        },
        {
          "id": "EUCAIM:BP1000220",
          "label": "Arm"
        }
      ]
    },
    "imageManufacturer": {
      "description": "Device manufacturer (DICOM tag 0008,0070), controlled vocabulary",
      "$ref": "https://raw.githubusercontent.com/EGA-archive/EUCAIM-Schema/refs/heads/main/Common/OntologyTerm.json",
      "examples": [
        {
          "id": "EUCAIM:IMG1000047",
          "label": "General Electric"
        },
        {
          "id": "EUCAIM:IMG1000044",
          "label": "Siemens"
        }
      ]
    },
    "dateOfImageAcquisition": {
    "type": "string",
    "format": "date-time",
    "description": "Acquisition date of the image (DICOM tag 0008,0022), in ISO 8601 date-time format (e.g. YYYY-MM-DDThh:mm:ssZ).",
    "example": "2000-01-01T00:00:00Z",
    "$comment": "Mandatory if available."
}

  },
  "required": [
    "imageStudyId",
    "disease",
    "imageModality",
    "imageBodyPart",
    "imageManufacturer",
    "dateOfImageAcquisition"
  ]
}

=== EGA-archive/beacon2-ri-tools-v2/files/deref_schemas/EUCAIM/ImageStudiesMetadata.json
{
    "imageStudyId": "",
    "disease": {
        "dateOfFirstTreatment": "",
        "diagnosis": {
            "id": "",
            "label": ""
        },
        "diseaseId": "",
        "imagingProcedureProtocol": {
            "id": "",
            "label": ""
        },
        "pathology": [
            {
                "id": "",
                "label": ""
            },
            {
                "id": "",
                "label": ""
            }
        ],
        "pathologyConfirmation": {
            "id": "",
            "label": ""
        },
        "treatment": [
            {
                "id": "",
                "label": ""
            },
            {
                "id": "",
                "label": ""
            }
        ],
        "tumorMetadata":{
    "tumorId": "",
    "tumorMarkerTestResult": {
        "id": "",
        "label": ""
    },
    "cancerStageCMCategory": {
        "id": "",
        "label": ""
    },
    "cancerStagePMCategory": {
        "id": "",
        "label": ""
    },
    "histologicGraceGleasonScore": {
        "id": "",
        "label": ""
    },
    "histologicGradeISUP": {
        "id": "",
        "label": ""
    },
    "tumorBIRADSAssesment": {
        "id": "",
        "label": ""
    },
    "tumorPIRADSAssesment": {
        "id": "",
        "label": ""
    }
},
        "yearOfDiagnosis": 0
    },
    "imageModality": {
        "id": "",
        "label": ""
    },
    "imageBodyPart": {
        "id": "",
        "label": ""
    },
    "imageManufacturer": {
        "id": "",
        "label": ""
    },
    "dateOfImageAcquisition": ""
}
