=== EGA-archive/beacon2-ri-tools-v2/ref_schemas/EUCAIM-Schema-main/PatientsMetadata.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Minimum patient attributes",
  "type": "object",
  "properties": {
    "patientId": {
      "type": "string",
      "description": "A unique identifier for the patient. Should match the Patient ID DICOM tag (0010,0020) and anonymization processes.",
      "example": "X123456"
    },
    "sex": {
      "description": "Biological sex at birth.",
      "$ref": "./Common/Definitions.json#/$defs/Sex",
      "examples": [
        {
          "id": "EUCAIM:COM1001370",
          "label": "Female"
        },
        {
          "id": "EUCAIM:COM1001366",
          "label": "Male"
        },
        {
          "id": "EUCAIM:COM1001288",
          "label": "Unspecified"
        }
      ]
    },
    "disease": {
      "description": "Disease information associated with the patient.",
      "type":"array",
      "items": {
        "$ref": "./Common/Matrixes/DiseasesMetadata.json"
      }
    },
    "imageStudy": {
      "description": "Imaging study information associated with the patient.",
      "type":"array",
      "items": {
      "$ref": "./ImageStudiesMetadata.json"
      }
    }
  },
  "required": [
    "patientId",
    "sex",
    "disease",
    "imageStudy"
  ]
}

=== EGA-archive/beacon2-ri-tools-v2/files/deref_schemas/EUCAIM/PatientsMetadata.json
{
    "patientId": "",
    "disease": [
        {
    "diseaseId": "",
    "ageAtDiagnosis": 0,
    "diagnosis": {
        "id": "",
        "label": ""
    },
    "yearOfDiagnosis": 0,
    "dateOfFirstTreatment": "",
    "pathologyConfirmation": {
        "id": "",
        "label": ""
    },
    "pathology": [
        {
            "id": "",
            "label": ""
        }
    ],
    "imagingProcedureProtocol": {
        "id": "",
        "label": ""
    },
    "treatment": [
        {
            "id": "",
            "label": ""
        }
    ],
    "tumorMetadata": {
    "tumorId": "",
    "tumorMarkerTestResult": {
        "id": "",
        "label": ""
    },
    "cancerStageCMCategory": {
        "id": "",
        "label": ""
    },
    "cancerStagePMCategory": {
        "id": "",
        "label": ""
    },
    "histologicGraceGleasonScore": {
        "id": "",
        "label": ""
    },
    "histologicGradeISUP": {
        "id": "",
        "label": ""
    },
    "tumorBIRADSAssesment": {
        "id": "",
        "label": ""
    },
    "tumorPIRADSAssesment": {
        "id": "",
        "label": ""
    }
}
}
    ],
    "imageStudy": [
       {
    "imageStudyId": "",
    "disease": {
        "ageAtDiagnosis": 0,
        "dateOfFirstTreatment": "",
        "diagnosis": {
            "id": "",
            "label": ""
        },
        "diseaseId": "",
        "imagingProcedureProtocol": {
            "id": "",
            "label": ""
        },
        "pathology": [
            {
                "id": "",
                "label": ""
            },
            {
                "id": "",
                "label": ""
            }
        ],
        "pathologyConfirmation": {
            "id": "",
            "label": ""
        },
        "treatment": [
            {
                "id": "",
                "label": ""
            },
            {
                "id": "",
                "label": ""
            }
        ],
        "tumorMetadata":{
    "tumorId": "",
    "ER":{"id": "", "label": ""},
    "PR":{"id": "", "label": ""},
    "HER2":{"id": "", "label": ""},
    "KI67":0,
    "PSA":0,
    "cancerStageCMCategory": {
        "id": "",
        "label": ""
    },
    "cancerStagePMCategory": {
        "id": "",
        "label": ""
    },
    "histologicGraceGleasonScore": {
        "id": "",
        "label": ""
    },
    "histologicGradeISUP": {
        "id": "",
        "label": ""
    },
    "tumorBIRADSAssesment": {
        "id": "",
        "label": ""
    },
    "tumorPIRADSAssesment": {
        "id": "",
        "label": ""
    }
},
        "yearOfDiagnosis": 0
    },
    "imageModality": {
        "id": "",
        "label": ""
    },
    "imageBodyPart": {
        "id": "",
        "label": ""
    },
    "imageManufacturer": {
        "id": "",
        "label": ""
    },
    "dateOfImageAcquisition": ""
}
    ],
    "sex": {
    "id": "",
    "label": ""
}
}
